services:

  mysql:
    image: mysql:8.0
    ports:
      - 3326:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databasestar:/databasestar
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck: #Checa el contenedor
      test: ["CMD", "mysqladmin" ,"ping","-h","localhost"]
      interval: 10s #Cada 10 segundos 
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  fastapi:
    build: ./app  
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - 8083:9000 #Adentro del contenedor el 9000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=movies
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./app:/app
volumes:
   mysql_data:
